---
- name: Install nginx on webserver
  hosts: webserver
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

- name: Install apache2 on appserver
  hosts: appserver
  become: true
  tasks:
    - name: Install apache2
      ansible.builtin.apt:
        name: apache2
        state: present
